// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZespolLib;

namespace ZespolServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210427174614_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ZespolLib.CzlonekZespolu", b =>
                {
                    b.Property<string>("PESEL")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataUrodzenia")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataZapisu")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Funkcja")
                        .HasColumnType("text");

                    b.Property<string>("Imie")
                        .HasColumnType("text");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("text");

                    b.Property<int>("Plec")
                        .HasColumnType("integer");

                    b.Property<string>("ZespolId")
                        .HasColumnType("text");

                    b.HasKey("PESEL");

                    b.HasIndex("ZespolId");

                    b.ToTable("CzlonkowieZespolow");
                });

            modelBuilder.Entity("ZespolLib.KierownikZespolu", b =>
                {
                    b.Property<string>("PESEL")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataUrodzenia")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Doswiadczenie")
                        .HasColumnType("integer");

                    b.Property<string>("Imie")
                        .HasColumnType("text");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("text");

                    b.Property<int>("Plec")
                        .HasColumnType("integer");

                    b.HasKey("PESEL");

                    b.ToTable("KierownicyZespolow");
                });

            modelBuilder.Entity("ZespolLib.Zespol", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("KierownikPESEL")
                        .HasColumnType("text");

                    b.Property<string>("Nazwa")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KierownikPESEL");

                    b.ToTable("Zespoly");
                });

            modelBuilder.Entity("ZespolLib.ZespolCluster", b =>
                {
                    b.Property<string>("Nazwa")
                        .HasColumnType("text");

                    b.Property<string>("ZespolId")
                        .HasColumnType("text");

                    b.HasKey("Nazwa");

                    b.HasIndex("ZespolId");

                    b.ToTable("ZespolClusters");
                });

            modelBuilder.Entity("ZespolLib.ZespolCluster+ZespolArchive", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ZespolClusterNazwa")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ZespolClusterNazwa");

                    b.ToTable("ZespolArchive");
                });

            modelBuilder.Entity("ZespolLib.CzlonekZespolu", b =>
                {
                    b.HasOne("ZespolLib.Zespol", null)
                        .WithMany("Czlonkowie")
                        .HasForeignKey("ZespolId");
                });

            modelBuilder.Entity("ZespolLib.Zespol", b =>
                {
                    b.HasOne("ZespolLib.KierownikZespolu", "Kierownik")
                        .WithMany()
                        .HasForeignKey("KierownikPESEL");

                    b.Navigation("Kierownik");
                });

            modelBuilder.Entity("ZespolLib.ZespolCluster", b =>
                {
                    b.HasOne("ZespolLib.Zespol", "Zespol")
                        .WithMany()
                        .HasForeignKey("ZespolId");

                    b.Navigation("Zespol");
                });

            modelBuilder.Entity("ZespolLib.ZespolCluster+ZespolArchive", b =>
                {
                    b.HasOne("ZespolLib.ZespolCluster", null)
                        .WithMany("ZespolHistory")
                        .HasForeignKey("ZespolClusterNazwa");
                });

            modelBuilder.Entity("ZespolLib.Zespol", b =>
                {
                    b.Navigation("Czlonkowie");
                });

            modelBuilder.Entity("ZespolLib.ZespolCluster", b =>
                {
                    b.Navigation("ZespolHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
